name: GitHub Security Scanner Alert

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Call Postman Github security scanner flow
        run: curl -X POST https://5de49fb59ffa4c948b51e9dd350d7304.flow.pstmn.io -d '{"data":"Github"}'
